/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.trainwatch.job.table;

import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Consumer;
import java.util.stream.Stream;

/**
 * A table generated by a script
 * <p>
 * @author peter
 */
public abstract class Molecule<T>
        implements Iterable<T>,
                   Atom
{

    private final List<T> elements = new LinkedList<>();

    protected final List<T> getElements()
    {
        return elements;
    }

    @Override
    public Iterator<T> iterator()
    {
        return elements.iterator();
    }

    public int size()
    {
        return elements.size();
    }

    public boolean isEmpty()
    {
        return elements.isEmpty();
    }

    public void clear()
    {
        elements.clear();
    }

    public T get( int index )
    {
        return elements.get( index );
    }

    public Stream<T> stream()
    {
        return elements.stream();
    }

    @Override
    public void forEach( Consumer<? super T> action )
    {
        elements.forEach( action );
    }

}
