/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.trainwatch.job.table;

import java.text.Format;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

/**
 * A table generated by a script
 * <p>
 * @author peter
 */
public class Table
        extends Molecule<Row>
{

    private final Map<String, Integer> headerIndex = new HashMap<>();
    private final Molecule<Header> headers = new Molecule<Header>()
    {

        @Override
        public void accept( TableVisitor t )
        {
        }

    };

    private List<TableStringFormat> formats;

    public Table()
    {
    }

    public Table( Iterable<Map<String, Object>> iterable )
    {
        Header h = newHeader();

        Iterator<Map<String, Object>> it = iterable.iterator();
        while( it.hasNext() ) {
            Map<String, Object> m = it.next();
            Row r = newRow();
            m.forEach( ( k, v ) -> {
                if( !h.contains( k ) ) {
                    h.newCell( k );
                }
                r.set( h.indexOf( k ), v );
            } );
        }
    }

    public List<TableStringFormat> getFormats()
    {
        return formats == null ? new ArrayList<>() : new ArrayList<>( formats );
    }

    public <T extends Format> T getFormat( int col )
    {
        return formats == null || formats.size() < col ? null : (T) formats.get( col );
    }

    public Table setFormat( int col, TableStringFormat f )
    {
        if( formats == null ) {
            formats = new ArrayList<>();
        }
        while( formats.size() < col ) {
            formats.add( null );
        }
        formats.add( col, f );
        return this;
    }

    public int getHeaderCount()
    {
        return headers.size();
    }

    public boolean isHeadersEmpty()
    {
        return headers.isEmpty();
    }

    public Header newHeader()
    {
        Header h = new Header();
        headers.getElements().add( h );
        return h;
    }

    public void forEachHeader( Consumer<Header> c )
    {
        headers.forEach( c );
    }

    public Row newRow()
    {
        Row row = new Row();
        getElements().add( row );
        return row;
    }

    public Row newRow( Object... args )
    {
        Row row = newRow();
        if( args != null && args.length > 0 ) {
            for( Object arg: args ) {
                row.append( arg );
            }
        }
        return row;
    }

    @Override
    public void accept( TableVisitor t )
    {
        t.visit( this );
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();

        accept( new StringTableVisitor( sb, FormatTableVisitor.getFormatters( this ) ) );

        return sb.toString();
    }

}
