/*
 * scope1   Test variable scoping
 *
 * Here we have in the main scope a=1 and as b is undefined its null.
 *
 * Then in the inner block we set a to 2 and b to 42.
 *
 * At the end, a should be 2 but b is null as it was set in the child,
 * so the outer scope has no knowledge of it.
 *
 */
job "scope1";
run as "test";
{
    // Test that a variable in the outer scope retains its value
    // when
    a = 1;
    log "before a is 1 = "+a;

    // b should be null as declared inside block
    log "before b is null = "+b;

    {
        log "block before a is 1 = "+a;
        a = 2;
        log "block after a is 2 = "+a;

        log "block before b is null = "+b;
        b = 42;
        log "block after b is 42 = "+b;
    }

    // Although changed inside block a should be changed
    log "after a is 2 = "+a;

    // b should be null as declared inside block
    log "after b is null = "+b;
}
